@enum EPSWhich begin
    EPS_LARGEST_MAGNITUDE = 1
    EPS_SMALLEST_MAGNITUDE = 2
    EPS_LARGEST_REAL = 3
    EPS_SMALLEST_REAL = 4
    EPS_LARGEST_IMAGINARY = 5
    EPS_SMALLEST_IMAGINARY = 6
    EPS_TARGET_MAGNITUDE = 7
    EPS_TARGET_REAL = 8
    EPS_TARGET_IMAGINARY = 9
    EPS_ALL = 10
    EPS_WHICH_USER = 11
end